import {Todo} from "./todo";

export const TODOS: Todo [] = [
    {
        id: 1,
        title: "Todo 1",
        content: "content todo 1",
        author: "John doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
    id: 2,
    title: "Todo 2",
    content: "content todo 2",
    author: "John doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
    },
    {
    id: 3,
    title: "Todo 3",
    content: "content todo 3",
    author: "John doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
    },
    {
    id: 4,
    title: "Todo 4",
    content: "content todo 4",
    author: "John doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
    },
    {
    id: 5,
    title: "Todo 5",
    content: "content todo 5",
    author: "John doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
},
{
    id: 6,
    title: "Todo 6",
    content: "content todo 6",
    author: "John doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
    },
    {
    id: 7,
    title: "Todo 7",
    content: "content todo 7",
    author: "John doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
},
{
    id: 8,
    title: "Todo 8",
    content: "content todo 8",
    author: "John doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
},
    {
    id: 9,
    title: "Todo 9",
    content: "content todo 9",
    author: "John doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
},
{
    id: 10,
    title: "Todo 10",
    content: "content todo 10",
    author: "John doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
}
]